CREATE TABLE User(
    id INT NOT NULL AUTO_INCREMENT,
    lastname VARCHAR(100) NOT NULL,
    firstname VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,.
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    UNIQUE(login)
)
ENGINE = INNODB;

CREATE TABLE Student(
    id INT NOT NULL,
    completed_qcm_count INT DEFAULT 0,
    average_score FLOAT DEFAULT 0,
    PRIMARY KEY(id),
    FOREIGN KEY(id) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE = INNODB;

CREATE TABLE Teacher (
    id INT NOT NULL,
    created_qcm_count INT DEFAULT 0,
    PRIMARY KEY(id),
    FOREIGN KEY(id) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE
)
    ENGINE = INNODB;

CREATE TABLE Topic(
    id INT NOT NULL AUTO_INCREMENT,
    description VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
)
    ENGINE = INNODB;

CREATE TABLE Qcm(
    id INT NOT NULL AUTO_INCREMENT,
    label VARCHAR(100) NOT NULL,
    author_id INT NOT NULL,
    topic_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(author_id) REFERENCES Teacher(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(topic_id) REFERENCES Topic(id)
)
ENGINE = INNODB;

CREATE TABLE Result(
    id INT NOT NULL AUTO_INCREMENT,
    assignment_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completion_date DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    score FLOAT,
    qcm_id INT NOT NULL,
    user_id INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(user_id) REFERENCES User(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(qcm_id) REFERENCES Qcm(id) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE = INNODB;

CREATE TABLE Question(
    id INT NOT NULL AUTO_INCREMENT,
    label VARCHAR(100) NOT NULL,
    time_limit INT,
    qcm_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(qcm_id) REFERENCES Qcm(id) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE = INNODB;

CREATE TABLE Proposal(
    id INT NOT NULL AUTO_INCREMENT,
    label VARCHAR(100) NOT NULL,
    is_correct BOOLEAN,
    question_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    FOREIGN KEY(question_id) REFERENCES Question(id) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE = INNODB;

CREATE TABLE Answer(
    result_id INT NOT NULL,
    proposal_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(result_id, proposal_id),
    FOREIGN KEY(result_id) REFERENCES Result(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(proposal_id) REFERENCES Proposal(id) ON UPDATE CASCADE ON DELETE CASCADE
)
ENGINE = INNODB;

-- Creation d'un trigger qui met à jour la moyen QCM à chaque mise à jour de la table resultat

DELIMITER //
CREATE TRIGGER UpdateAverageScore AFTER UPDATE ON Result
    FOR EACH ROW
BEGIN
    UPDATE Student
    SET average_score = (
        SELECT ROUND(AVG(score) * 100) / 100
        FROM Result
        WHERE Result.user_id = Student.id
    ), completed_qcm_count = (;
        SELECT COUNT(*)
        FROM Result
        WHERE Result.user_id = Student.id AND Result.completion_date IS NOT NULL
    )
    WHERE Student.id = NEW.user_id;
END //
DELIMITER ;