export const ERRORS = {
  AUTH: {
    NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
    INVALID_PASSWORD: "INVALID_PASSWORD",
    INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
    INVALID_OR_EXPIRED_REFRESH_TOKEN: "INVALID_OR_EXPIRED_REFRESH_TOKEN",
    FAILED_TO_UPDATE_REFRESH_TOKEN: "FAILED_TO_UPDATE_REFRESH_TOKEN",
  },

  USER: {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
    USER_ID_REQUIRED: "USER_ID_REQUIRED",
  },

  QCM: {
    QCM_NOT_FOUND: "QCM_NOT_FOUND",
    INVALID_LABEL: "INVALID_LABEL",
  },

  QUESTION: {
    QUESTION_NOT_FOUND: "QUESTION_NOT_FOUND",
    NO_ANSWERS_FOUND: "NO_ANSWERS_FOUND",
  },

  PROPOSAL: {
    PROPOSAL_NOT_FOUND: "PROPOSAL_NOT_FOUND",
    PROPOSAL_ID_REQUIRED: "PROPOSAL_ID_REQUIRED",
    PROPOSAL_ID_MUST_BE_A_NUMBER: "PROPOSAL_ID_MUST_BE_A_NUMBER",
  },

  STUDENT: {
    STUDENT_NOT_FOUND: "STUDENT_NOT_FOUND",
  },

  SESSION: {
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    SESSION_AND_PROPOSAL_ID_REQUIRED: "SESSION_AND_PROPOSAL_ID_REQUIRED",
  },

  COMMON: {
    FIELD_MISSING: "FIELD_MISSING",
    PARAMETERS_MUST_BE_VALID_NUMBERS: "PARAMETERS_MUST_BE_VALID_NUMBERS",
  },
};
